### ISSUE TITLE
Compile Data - BDS

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#11]
4. BDS
 - Lengths
 - Ages

**Comment by okenk** [comment]
- [ ] Collect data on double reads from Patrick to estimate ageing error. 
- [ ] Get maturity data from Melissa Head

**Comment by brianlangseth-NOAA** [comment]
@aliwhitman, @tsoutt, @KSten

Commercial age samples include both surface reads and break and burn samples. What is your preference for keeping or excluding surface reads for comps? In the previous canary assessment, both groups were kept and were expanded separately and each had their own ageing-error matrix. Im inclined to maintain that approach as a starting point, but have a feeling that the benefit of including that level of complexity may be low. The years where surface reads are available are around 5 years before the start of using break-and-burn. 

Here are the sample sizes of commercial age samples based on the state specific ageing method.
            O          W 
  1        31399    0     
  2        3931      0     
  9        0            0     
  B        0        28332
  S        0          3887
  <NA>2         1605

The density of ages for each method is shown here. Surface reads tended to be older, so either due to older fish existing when surface reads versus when break and burn was done, or surface reads tend to run on the older side. 
![image](https://user-images.githubusercontent.com/27824606/212168419-ceae8292-5317-4b02-b0c8-4bf66eee57f8.png)

**Comment by aliwhitman** [comment]
I would say that the approach taken in the last assessment should be the default and see no issues moving forward with that.   We don't typically age Canary (Pat's lab usually handles that species for us).  I checked with Mark T. (our age reader) and he had general concerns about using surface reads at all, but he also mentioned that (a vague recollection) Pat may have re-aged a subsample of those earlier surface reads to determine a conversion factor.  Perhaps something to check out!

**Comment by tsoutt** [comment]
For WA, almost all the pre-1981 otoliths were surface aged. Some otoliths collected  in 1981 and 1982 were both surface and BB aged. Getting rid of surface ages will get rid of age composition for early years. You can use the double reads in 1981 and 1982 to see if there are biases.

**Comment by brianlangseth-NOAA** [comment]
@tsoutt and @KSten

Ive finally gotten around to applying our usual filters to commercial bds data. I see that there are 8830 samples in pacfin bds that are in canadian or puget sound PSMFC areas. The number of samples and areas are below. We plan to exclude these. Do you have an issue with this? 

1412 samples in area 5A
1726 samples in area 5B
15 samples in area 4A
5677 samples in area 3D

**Comment by tsoutt** [comment]
I good with that.

**Comment by brianlangseth-NOAA** [comment]
@tsoutt and @KSten

Another question. There are around 700 ages in pacfin bds without a final best age determination but with at least one age value provided. All of these are from WA, typically in the '80s. Typically our approach when no final age is available is to average across the provided age values. I plan to keep these samples. Do you see an issue with this? I know WA has a routine for determining best age.

**Comment by tsoutt** [comment]
Yes, if the difference between two reads are less than 2 years, we randomly select one. If the difference is more than 2 years, the age readers will need to work together in front the microscope to reconcile. In this case, we may get an age that is different from the first 2 reads in some rare cases.
As long as it is documented how the best ages are determined, I think it will work.

**Comment by brianlangseth-NOAA** [comment]
After a discussion with @tsoutt, because the samples here are a relatively small percentage of the total number of ages for any given year (at most 6%), and that taking the average of samples doesn't use an actual age read (rather it uses an average) Ive decided to exclude these unknown ages.

**Comment by KSten** [comment]
I have added the Canary Biodata for Sport and Research fish here: https://docs.google.com/spreadsheets/d/1LMavfMnc9P2JXnF2_clKjVdH7dBfnGFc/edit?usp=share_link&ouid=100258823246786665986&rtpof=true&sd=true

I will update this when we get the final ages in, they should be done ageing in March.

Research biodata has two (possibly 3 depending on how the WDFW nearshore rockfish survey is used) surveys in there.  IF IPHC is used as an index. there is biodata associated with their Rockfish catch; it is labeled in column x(project_name) as IPHC Longline Survey.

Please let me know if there are any questions!

**Comment by tsoutt** [comment]
@brianlangseth-NOAA What indices do you plan to include in the Canary assessment?

**Comment by brianlangseth-NOAA** [comment]
Last assessment used Triennial, WCGBTS, and pre-recruit. We will include those though explore omitting triennial. We are also exploring state surveys, which I think would include your nearshore one. If there are others (i.e. the IPHC) that we should use, let us know.

**Comment by tsoutt** [comment]
Canary has been showing up more in sport fishing. Will you consider using our dockside interviews as an index? I don't know if you "should" include IPHC survey or if it is informative. Just want to bring it up to your attention.

**Comment by brianlangseth-NOAA** [comment]
Feel free to edit the post in issue #39 and add any potential surveys. In our original discussion we talked about WA hook and line for 2019-2021. perhaps the one here is that one.

**Comment by brianlangseth-NOAA** [comment]
Commit 2b670d1 added Oregon length bds data provided by Oregon. Ages not yet provided by state though have them in RecFIN

**Comment by brianlangseth-NOAA** [comment]
Filling in information from emails with @JohnBudrick on Feb 2 and 3 about historical CA rec data. The available data are as follows based on historical datasets that occur in areas where Canary are found (i.e. north of Pt Conception), and I list in order of priority

- [ ] 1989-1999 DebWV data 
- [ ] 50's-60's dockside sampling (has a counts column so lengths need to be multiplied by counts)
- [ ] late 70's-80's CCRS data

Historical datasets south of Pt Conception (Crooke and Ally and Vicky Wine's study) need not be explored. 

The dockside sampling from the 50s-60s have a limited geographic scope to around Monterey Bay. The same is true of the CCRS data. John doesn't think either is sufficiently representative spatially to warrant inclusion, and he prefers the more balanced sampling of MRFSS, RecFIN, and possibly DebWV. The dockside sampling would represent the only data available going that far back, which could warrant there inclusion though it is unlikely to change results much. The CCRS data are during a period where more samples are available, however they do include sex data. Based on sample size, these also are unlikely to change model results. These can be explored outside the model to see if there are large differences. The DebWV data sampled mostly north of Ft. Bragg so would also have limited geographic scope, but has a more structured sampling design. 

Whether we include these are not, we should include a short write up describing the scope and overall sample sizes.

**Comment by brianlangseth-NOAA** [comment]
I added explorations of the historical rec data in california in commit 6cb2328. 

@JohnBudrick, the figure below shows that the lengths in the CCRS data differ from those in MRFSS in overlapping years. We were already leaning to exclude these due to their limited geographic scope. The large differences in length in overlapping years adds support to that thought. Because the CCRS data differ so much with mrfss, @okenk and I are also not inclined to include the 50-60s dockside samples due to the same concern of limited geographic scale influencing length, even though there are more samples in the 50-60s. I plan to include a brief description of these data in the write-up, with justification of our choices, but do not plan to include lengths from the CCRS or dockside sampling within the model itself. 

![CA_historical_recLen_comparison_noDebWV](https://user-images.githubusercontent.com/27824606/229262665-5cf55298-9f06-4ae4-a27e-6ae8e0c3aab7.png)

**Comment by brianlangseth-NOAA** [comment]
Note that for copper rockfish, the DebWV data was found to have lengths that were likely duplicated in the mrfss data for 1997 and 1998 (see [this issue](https://github.com/pfmc-assessments/california-data/discussions/5)), and thus that STAT removed PC samples from mrfss for those years and replaced with debWV samples for generating comps (see [this code script](https://github.com/pfmc-assessments/copper_rockfish_2023/blob/main/R/recfin_bds/process_rec_bds.R))

I cannot confirm this occuring for canary because the DATE1 fields seems off in the mrfss data but there are a lot of similar lengths (mrfss LNGTH converted back to total length using echeverria and lenarz relationship compared to the debWV TL measurements).

**Comment by JohnBudrick** [comment]
I can put together counts and more specifics on the geographic limitations of the surveys if need be.

**Comment by JohnBudrick** [comment]
They differ in a way that is the reverse of my expectation, but either way, the MRFSS sampling is more representative of the full distribution in California.

**Comment by brianlangseth-NOAA** [comment]
We have all of the BDS data now. Issue #32 deals with putting them in comps for entry into SS3. Closing now
