### ISSUE TITLE
Compile Data - Data warehouse Surveys

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#12]
5. Surveys
 - WCGBTS
 -  Triennial
 - Confirm all others have minimal data

**Comment by brianlangseth-NOAA** [comment]
@okenk Would you like to start exploring the survey data to get catch, comps, and biological relationships? Catch would be a good first step and can be pulled using the nwfscSurvey package, looks like we use <[PullCatch.fn.R](https://github.com/pfmc-assessments/nwfscSurvey/blob/main/R/PullCatch.fn.R)>. Bio data is probably next easiest (looks like <PullBio.fn.R>, then comps (looks like <SurveyLFs.fn.R> and <SurveyAFs.fn.R> and <SurveyAgeAtLen.fn.R>

**Comment by okenk** [comment]
I am confused what you want me to do? I can of course run those functions. And then...?

**Comment by okenk** [comment]
What are the strata to use for expanding the length and age composition samples? Note that there are no default latitudes/depths in `nwfscSurvey`, the assessment handbook includes no description of how to expand length and age compositions, and nothing is described in the previous stock assessment. 

@kellijohnson-NOAA @chantelwetzel-noaa @iantaylor-NOAA this seems like it may be a documentation gap.

**Comment by chantelwetzel-noaa** [comment]
This is a great question which may not be clearly spelled out in the documentation or the example script. The user selected stratification by latitude and depth input into the CreateStrataDF.fn function will calculate the survey area within each of the strata. The output of the CreateStrataDF.fn can then be passed to the CheckStrata.fn to check how many observations are within each strata by year to ensure the observation number is sufficient. The strata area is then passed to either the SurveyLFs.fn or the SurveyAFs.fn where the lengths or ages will be first expanded up to the tow level and then to the strata level based on the areas calculated within the strata by the CreateStrataDF.fn.  

This general information should be added to our assessment handbook. Note, that this data expansion approach is essentially a design-based approach, however, we do not use the design-based index but rather a spatial and spatiotemporal modeling approach.  The impact of expanding the composition data via a different method than the index estimation has been the subject of discussions within the SSC.  There is more detail that could be added here but it may be better suited for an meeting discussion.

**Comment by brianlangseth-NOAA** [comment]
@okenk I will help you Kiva. Lets schedule a time to discuss. 

Chantel's discussion is related to the comps. Those are the hardest in my opinion given the expansion routines. I still get confused by them. 

Getting the data pulled, and starting to run biological calls for W-L relationships and seeing what maturity data is there would be a better first step.

**Comment by brianlangseth-NOAA** [comment]
Things to do for the survey data (WCGBTS and Triennial) include

- [ ] Calculate catches - break down by state. Unsure if we have to expand what is reported but we can check with values from last assessment. 
- [ ] Composition data - do both expanded age comps and length comps (look at [survey_lcomps.R](https://github.com/pfmc-assessments/lingcod/blob/main/R/survey_lcomps.R) and [survey_acomps.R](https://github.com/pfmc-assessments/lingcod/blob/main/R/survey_acomps.R) in the lingcod repo). These files communicate my logic for use of depth stratas. The age comp file also has functionality for calculating CAAL (conditional age at length)
- [ ] Maturity data - confirm there exist maturity data in the datasets.
- [ ] Growth data - if we use CAAL then growth can be estimated in the model. However, we will want to explore these to compare to the thesis describing growth differences, and confirm those are indeed different. I did this for survey data for lingcod in [lingcod_LW_LA.R](https://github.com/pfmc-assessments/lingcod/blob/ec6d583c40bae80fe5bee064878578434bd457ef/data-raw/lingcod_LW_LA.R). Another file for lingcod does the same thing [survey_biological_exploration_estimation.R](https://github.com/pfmc-assessments/lingcod/blob/ec6d583c40bae80fe5bee064878578434bd457ef/data-raw/survey_biological_exploration_estimation.R) but is more geared toward generating figures than exploring. 
- [ ] Weight-Length data - files for growth can be used here too

**Comment by chantelwetzel-noaa** [comment]
Historically, there was a practice to include research removals from the surveys (or other data sources) in the assessment of species that were classified as overfished (e.g., canary and Pacific ocean perch). However, the SSC commented during the 2017 review of POP that included the removals from the surveys may not be necessarily since there are so small and that it is not standard practice across all groundfish stock assessments.  Ultimately, the decision is up to you two, but I wanted to add this historical context for your consideration of what is appropriate in the 2025 assessment.

**Comment by iantaylor-NOAA** [comment]
Hi All,
I have two quick comments. 

**Comp expansions**
First, regarding expansion of comp data, we had a team discussion after Thorson and Haltuch published "Spatiotemporal analysis of compositional data: increased precision and improved workflow using model-based inputs to stock assessment" a few years ago: https://cdnsciencepub.com/doi/full/10.1139/cjfas-2018-0015 and concluded that the spatiotemporal expansion was similar enough to the designed-based approach that there wasn't obvious need to make the switch, but any STAT who were excited to try the new approach was welcome to do so. None did. With the switch from VAST to sdmTMB, I'm not sure how much harder or easier a spatiotemporal expansion of comp data would be, but I'm personally not excited to go down that road quite yet. I don't have any guidance on stratification for the design-based approach, sorry.

**Research catch**
Second, here's a tiny bit more regarding research catch, as mentioned by @chantelwetzel-noaa. In the earlier days we didn't have the option to associate catch with surveys in stock synthesis so this got lumped with some fishing fleet which has may had have different selectivity. In recent years, SS3 has the option for catch associated with the surveys. However, I would be cautious about doing so unless the total survey catch is significant compared to the total mortality (at least 1%). Adding catch associated with the surveys has the potential to add a bunch of unnecessary complexity to forecasts and fleet allocation calculations with relatively little benefit. Also, not all research catch is associated with the survey fleets we are modeling.

**Comment by kellijohnson-NOAA** [comment]
Spatiotemporal expansion of composition data is not possible in {sdmTMB}, at least in the same way that {VAST} does it, because "categories" which are used to represent age or length classes are not possible in {sdmTMB}.

**Comment by okenk** [comment]
We will need to select strata for the design-based survey comps. It looks like using the sampling effort strata from the survey is the standard here. However, canary rockfish disappear well shallower than the end of the second depth stratum, so expanding out into the full stratum [is not advised](https://github.com/pfmc-assessments/lingcod/issues/21#issuecomment-840871608). 

Based on this figure, I am planning on expanding out to 350m depth, after which canary disappear from the survey.
![image](https://user-images.githubusercontent.com/205013/213013836-a6968085-e84a-4b13-bf94-921cbdf2a0f1.png)

**My plans for the strata are:
latitudes: 32-34.5, 34.5-49 degrees
depths: 55-183, 183-350 meters**

**Comment by brianlangseth-NOAA** [comment]
@okenk Im fine by that. Is this for the WCGBTS? Is the strata south of Pt. Conception typical (presumably due to a different sampling scheme)?

**Comment by okenk** [comment]
I got the splits from [this document](https://docs.google.com/document/d/1pq7D6ZYbpbgc-7v2qwcCyr3SCqDfBNxcPPq082jwnYQ/edit) I found linked to in the assessment handbook.

**Comment by iantaylor-NOAA** [comment]
Good to see the handbook being useful.

It also says "Starting in 2004, there’s a change in sampling intensity north and south of 34.5, so this strata boundary should be included (unless there’s some specific reason not to)"
https://pfmc-assessments.github.io/pfmc_assessment_handbook/01-data-sources.html#summary-of-noaa-fishery-independent-trawl-surveys-used-for-west-coast-assessments

**Comment by brianlangseth-NOAA** [comment]
See this [issue](https://github.com/kellijohnson-NOAA/indexwc/issues/9#issuecomment-1546933071) on how to deal with 2004 for the triennial. Unsure how we will handle this this cycle.
