### ISSUE TITLE
PacFIN catches

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#19]
@chantelwetzel-noaa This may be a silly question but should I NOT filter out records with Canary in the SPECIES_CODE_NAME from the pacfin file you provided? Right now I doing grep("CANARY", catch$SPECIES_CODE_NAME). Im guessing that I should not.

Ive done the [comparisons](https://drive.google.com/drive/folders/1fleYIaLvdIYMLv14--P1804akQvnWu5J?usp=sharing) between catches in PacFIN with the 2015 values from the file in the 2015 canary catch archives MASTER_Total_Mortality_Catches_State_Gear_v6_preferred_foreign.csv. Recent values are almost always less than 2015 values. My major concern is that Im missing years for Oregon and California in the recent pull and Im severely underestimating CA catches. I can see the NOMINAL_TO_ACTUAL_PACFIN_SPECIES_NAME is always CNRY despite the SPECIES_CODE_NAME being a whole suite of various species.

**Comment by chantelwetzel-noaa** [comment]
I don't think there is enough information in the figure for my to understand the comparison. Is the blue or the red the new data? If the new data is the red, I see approximately the same amount as the blue line for CA when just summing up landing by state and year. Are there removals that are not being included in the trawl and non-trawl gear?

Are the recent year differences being compared against the landings tab in the old spreadsheet? Just wanted to double check that you are not accidently comparing the landings+discard from 2015 to only landings from the new day.

**Comment by brianlangseth-NOAA** [comment]
Confirmed that I do not filter out records from the pacfin file that chantel provided based on species. Use all. Catches align very well now!

**Comment by brianlangseth-NOAA** [comment]
@chantelwetzel-noaa I notice some puget sound data is included in the file you provided. cleanPacFIN is for bds data. Are there defined ways available to our group on how to remove Puget Sound catches from PacFIN?

**Comment by chantelwetzel-noaa** [comment]
What field are you looking at? I think the next question we would need to look at is whether that is where the fish was landed.  I looked at the PACFIN_CATCH_AREA_CODE and did not see 4a which is the area I think associated with Puget Sound.

**Comment by brianlangseth-NOAA** [comment]
@kellijohnson-NOAA is looking into this too. You are correct that all of those areas are 1-3, apart from some named areas. The field I am confused by is REGION_NAME has a "WA_INTERNAL_MARINE" category that includes SUBREGION_NAMES "STRAIT OF GEORGIA", "SAN JUAN", "METRO PUGET SOUND", and "NE OLY & KITSAP PENINSULAS", which sound very Puget Sound-y.

In general, I know we've moved to full and non-filtered datasets now. Apart from maybe filtering for puget sound, is the only other filtering to remove research catches? I dont need to be checking for mexico or canada catches do I?

**Comment by brianlangseth-NOAA** [comment]
Thanks to @kellijohnson-NOAA and @chantelwetzel-noaa for assisting. I am fairly confident no puget sound records are included in the pacfin full. There are 44 records where ORIG_PACFIN_CATCH_AREA_CODE equals 4A. However, from previous emails with the state, 

"For near shore species, we have included catches from recreational catch area 4B and commercial catch area 29 (WDFW codes) in the assessments.  This is the area east of the Bonilla-Tatoosh Line.  Area 29 is included in PSFMC 4A instead of 3B".

It appears that those 4A records are now appropriately listed as 3B. I have emailed Theresa for confirmation. Apart from that I see no need for further filtering.

**Comment by brianlangseth-NOAA** [comment]
Theresa confirmed in email on 11/8 that "We always include commercial area 29 and recreational area 4B (state codes)" thus Im going to keep those records in and assume there are no further Puget Sound records. 

Closing this issue
