### ISSUE TITLE
Compile Data - Pre-recruit survey

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#22]
Separate from #12

- [x] Obtain pre-recruit survey data
 
@okenk emailed John Field about the pre-recruit survey

Where might I find the updated data from this survey? Is it hosted online? Does it have data from 2022 yet?

**Comment by brianlangseth-NOAA** [comment]
John's response was in short: "Briefly, I will very happily provide both indices and raw data in the fairly near future.  Our 2022 database is not quite finalized" and "we do have every intention to get you both potential indices and raw data should you like to explore by very early 2023"

My take is that he will provide the information to us.

More details from John: "As for data- it is served online- we also have an R package that Tanya Rogers has written to help extract results, standardize catches in either numbers, mass, or for spp. with age data, 100 day old equivalents.  The package can pull data from ERDDAP, although ERDDAP currently only includes data through 2018 (should go to 2020 shortly), and we have not posted the age data on ERDDAP so the 100 day old equiv. counts can't be done that way.  We're working on improving all of this, but of course it all takes time. Anyway- Tanya's github provides a bit of background if you are interested- https://github.com/tanyalrogers/RREAS."

**Comment by okenk** [comment]
Raw data and first-draft index provided by @tanyalrogers and John Field on 1/21 and 1/22.

**Comment by brianlangseth-NOAA** [comment]
After a number of conversations we settled having a coastwide index, with partitioned out indices for WA, OR, and CA. 

We had discussions about whether even to use Washington data, and originally thought it would be excluded because the sampling is so sparse, and thus a state-specific index would be a little bit questionable. However, partitioning the state-specific index on a coastal model suggests there is data sharing going on, giving just slightly more support for generating a washington index. We will emphasize the few samples in Washington. 

Although partitioning a coastwide model to state may reduce the independence of the state indices (where having a year:state interaction would keep them separate), tanya was concerned about being able to run the state specific index. Furthermore, she tried a partitioned coastal model and state specific models in a combined black+yellotail run and found them to be nearly identical. 

When using the partitioned state specific indices, Tanya recommends removing years where no sampling took place (which is different then years where sampling occurred but no canary were caught).

**Comment by brianlangseth-NOAA** [comment]
Final indices and data merged in #54. Closing now.
