### ISSUE TITLE
Compile data - H&L survey

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#24]
John Harms reached out with numbers of biological samples for canary in the hook and line survey. There are 393 lengths of canary and 193 ages, with 177 otoliths currently unaged. These data have limited information content given canary is not common South of pt. conception and growth likely differs with the rest of california, however this is a data source that is larger than I had assumed.

At the moment, these data are probably left as a data that is available and could be explored as opposed to data that should be.

**Comment by okenk** [comment]
For reference, there are 5421 ages already read in the WCGBTS data between 2003 and 2016, as compared to the 193 from H&L.
