### ISSUE TITLE
Create sa4ss report files

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#34]
Add the sa4ss report files. Update packages following [sa4ss readme](https://github.com/pfmc-assessments/sa4ss). 

Use folder structure as described in the sa4ss discussions ([#71](https://github.com/pfmc-assessments/sa4ss/discussions/71)) though do not plan to use our github as an Rpackage

**Comment by okenk** [comment]
Hey, can you update sa4ss and redo this? I usually publish with my middle initial. Thanks!

**Comment by kellijohnson-NOAA** [comment]
what is your initial?

**Comment by okenk** [comment]
I already put it in {sa4ss}. Brian had added me to this list of authors, but I noticed everyone else's names had middle initials. So if you pull the current version on github it should work.

**Comment by brianlangseth-NOAA** [comment]
Roger Kiva. My adding of your name didn't actually work, but I saw sa4ss [issue #76](https://github.com/pfmc-assessments/sa4ss/issues/76) and trust that is why sa4ss yelled at me and said you weren't in the authors.csv even when you were.  I ended up manually editing our 00authors.md and our authors.csv and now it renders correctly.

**Comment by okenk** [comment]
Ah got it. Can you fix the initial then in the canary repo? It is L. It is on all of my papers. I can't find the authors.csv file.
