### ISSUE TITLE
Spatial modeling - mirroring survey q

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#35]
Related to #17 but placing as its own issue

@iantaylor-NOAA emailed about mirroring q for the surveys. The previous assessment estimated q separately for each area, yet there is an option to mirror q in the assessment. Ian found in a [previous presentation](https://docs.google.com/presentation/d/1q4PBPKehFkvzRbs4wewAfKkYt6803Yi9uMSxiLuiJDM/edit#slide=id.g54e6bba981_1_102) that doing this made a large difference. 

Im not surprised by this, and based on what Ian found the fits when mirroring are very poor, so Im not so sure why one would want mirror anything. Something for exploration. 

- [ ] Look into whether mirroring survey q among areas makes any sense

**Comment by iantaylor-NOAA** [comment]
It's possible that mirroring only makes sense for species that primarily occur in trawlable habitat where the biomass estimate isn't based on an implicit extrapolation from observations in trawlable to untrawlable (the ratios of which differs by area). 

I think when no mirroring is done, I think it's worth looking at the q estimates to see if anything can be learned by how they differ. For Canary in 2015, the WCGBTS q values were q CA = 0.73, q OR = 0.38, q WA = 0.56. I think that means that the VAST biomass for CA was 73% of the biomass that the model estimates based on the index trends and the OR estimate was half as much, implying that some combination of the OR sampling and the VAST extrapolation is just missing more Canary.

**Comment by brianlangseth-NOAA** [comment]
Im at a spatial modeling workshop and most users have assumed the same q across regions within their analysis. Much of those are based on modeling realities (estimating separate q was not realistic). But, it also depends how the indicies were generated. For example, f the indices all come from the same analysis, and scaling is implicit in that analysis, then some measure of q (with respect to scaling) is being implied and thus there is implicit differences in q. I wonder if that is what was done for canary. If the analyses are different though, the informating on scaling may not be comparable across areas, and I wonder if the assumption of "the same q across regions" is needed.

**Comment by brianlangseth-NOAA** [comment]
Closing because did not do spatial model
