### ISSUE TITLE
Compile data - Indices

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#39]
Potential or for sure indices to explore. Edit this post to add more. Things looked at but not used can have a few sentences in the write up. Many are from initial discussions as noted in our [notes doc]((https://docs.google.com/document/d/12VAxNXS2dfjmPMfYiBnHOxxtnN2277g_/edit)))

**For sure**
See issue #12 for WCGBTS and Triennial
WCGBTS - Kelli is doing index development
Triennial - but perhaps not in final base. Unsure who is doing index
- [x] Pre-recruit - Tanya Rogers is looking into index development (see commit c87fc7c)

**Not used but there**
- [x] WA olympic coast YOY survey (NOAA) - looked into and have summary but wont use in model
- [ ] ~OR nearshore logbook - Ali does not recommend~
- [ ] ~OR Marine reserves longline - not yet mature~
- [ ] ~OR ROV data - not a lot of canary~
- [ ] ~OR SMURF data - not a lot of canary~ (see Ali's comment below)
- [ ] ~IPHC - potential (see comment in #11) @KSten said low catch rates of canary at meeting on 1/25. In the washington research data there are length samples from IPHC, around 20 per year so sample size is not large.~
- [ ] ~WA rec dockside interview - potential (see comment in #11). Not planning to do dockside due to canary being more trawl species, dockside having concerns with accurate effort estimation, and concerns on retentions due to regulation history~
- [ ] ~OR ORBS rec survey - many samples but Ali suggested at-sea charters (below) if want rec index~

**State potential**
- [x] WA hook and line survey (provided via email from Theresa on April 11). Likely wont use due to limited years of data (4 plus limited 2020)
- [x] CA ROV survey - potential (see Budrick email about results). Likely wont have due to limited years of data (2 super periods). UPDATE: Provided values and write up via email from Budrick on May 1. 
- [ ] OR rec at sea observers - potential (see notes doc)
- [ ] ~OR video lander data - seems promising. Used for quillback and lingcod. Canary are common. May be best as appendix as its a one-off estimate rather than an index~
- [ ] OR marine reserve hook and line - @aliwhitman to spearhead and look at data

**Comment by tsoutt** [comment]
Rec dockside interview is not the same as our hook and line surveys. Dockside interview is fishery based. Hook and line surveys are scientific surveys conducted by WDFW or IPHC. WDFW nearshore hook-and-line/rod-an-reel survey was reviewed by SSC in 2022.

**Comment by aliwhitman** [comment]
I can provide an update on the OR SMURF data - when I met with the OSU researchers who are in charge of these data, there were not a lot of canary and they didn't recommend pursuing it at this time.  

Otherwise, the OR state potential list is what I have as well!  Some of those may end up on the "there but not used" list once I really dig into them.

**Comment by brianlangseth-NOAA** [comment]
@okenk I looked at the IPHC website: https://www.iphc.int/data/fiss-data-query and downloaded the non-halibut catch data into our google drive folder. There is a total of 178 fish from 1999-2022. Therefore we can check this box off as that is not enough samples to generate an index from.

**Comment by brianlangseth-NOAA** [comment]
Closing because document outlines many of the indices considered here but not ultimately done
