### ISSUE TITLE
Convert Washington rec landings from numbers of fish to MT

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#52]
Washington recreational data is provided in numbers. Stock synthesis can handle this, however having a mix of numbers and weights for fleets when making projections is complicated. Previous assessments have used numbers but converted numbers to weight for the projections (2017 yellowtail rockfish and 2017 lingcod) or iteratively solved for entry in numbers to obtain the desired ACL in weight (2021 copper rockfish and 2021 quillback rockfish) or converted catch in numbers to catch in weight prior to input into stock synthesis. 

As was done for 2021 lingcod ([see their issue #30](https://github.com/pfmc-assessments/lingcod/issues/30)) and in consultation with @tsoutt, we plan to convert numbers to weight by using the average length from recreational bio data of retained fish, then convert average length to average weight using a WL relationship. Whether to use RecFIN's (as provided by Theresa L-W:  a = 1.04058E-08	b = 3.084136662) or the survey relationship likely does not matter as WL relationships are pretty robust. We plan to use the one provided by Theresa.

**Comment by brianlangseth-NOAA** [comment]
@tsoutt and @KSten Ive looked into converting sport rec removals in numbers of fish to metric tons. The reality is that the length samples are pretty sparse or non-existent for many years. This requires some decisions on how to approach. @okenk have discussed and there are a few options we can use, described below. 

We would like you guidance as to which you would prefer? Do you have a preference? I am leaning towards option 2 because it assumes that lengths in years with very few estimates are unlikely to be near the true mean, it defines a borrowing scheme whereas RecFIN's and MRFSS is more of a black box, and it doesn't use RecFIN and MRFSS, which is consistent with the preference to use the Sport data in the first place. 

Now to the option
1. The first option is to use the data as is and assume, regardless of sample size, the data are correct. The mean length for each year of data within the sport bds file @KSten provided, along with the number of lengths in each year are below. The left y-axis is the number of length samples within a year, and is for the barplot. The right y-axis is the mean length estimate within a year. As you can see, mean length varies over time quite a bit, and the sample sizes are low in many years. For this option, we would use the yearly mean length for years with data (the points), and for years with no data, use the overall (unweighted) mean across years with data (the dashed line).

![image](https://user-images.githubusercontent.com/27824606/227269315-6452f4c2-c8e8-4929-9e18-4b414c58011e.png)
 
2. This option borrows lengths from nearby years to overcome small sample size issues, and blocks time periods when calculating overall mean length for years without data. Changes from the figure above are shown below; where red dots indicate years where borrowing adjusts the yearly estimate from the original value (white dots), black dots indicate years with length kept as is, and the dashed lines indicate the overall (unweighted) mean within specific blocks that would be used for years without data. The block time periods come from the rec regulations you provided, which are reproduced in #42, and are <1999, 2000-2003 (reduced bag limits), 2004-2016 (non-retention), and 2017-2022 (post non-retention). I have chosen 10 as the indicator of small sample size. This is arbitrary as any number could be used, but many years have sample sizes in the teens, so increasing this choice to a higher sample size would require more borrowing. 

![image](https://user-images.githubusercontent.com/27824606/227273221-1b223129-e492-4b45-955d-6f11fa7e4320.png)

3. The final option is to use RecFIN and MRFSS estimates. RecFIN reports total removals by N and by MT, so we could divide those two values each year to get a weight estimate for that year which we could then multiply by the numbers of fish we have from the sport data. RecFIN runs from 2004-2022. I have yet to confirm whether MRFSS has a number field I can use along with WGT_AB1_MT to determine weight.

**Comment by brianlangseth-NOAA** [comment]
@EJDick-NOAA provided a link to a publication ([Dick et al. 2021](https://reader.elsevier.com/reader/sd/pii/S0165783621001302?token=7F8209D816370BB29AF851AA3E42D11F506F59D76AE22D5FF63469CE8BFF6D8FB785431B8A9265387805FF3F85E10B05&originRegion=us-east-1&originCreation=20230323171932)) about model based estimation of average weight

**Comment by okenk** [comment]
Thanks for doing all this work Brian. I agree that option 2 seems reasonable. I also think you pointed out none of these results in particularly different time series by weight, right? Especially when considered relative to the volume removed in the trawl fishery.

**Comment by brianlangseth-NOAA** [comment]
@okenk I plotted the overall removals by MT for option 1 and 2 and there were quite similar. This is due to there being few changes in length among those two options. Other options (i.e. option 3) or other choices than 10 for the cutoff of small sample sizes could change things. 

Since 2000 the rec fleet makes up a non-trivial proportion of the Washington removals. Its the minority, but not so small. 2002-2003 and 2021 and 2022 are the years with the high length sample sizes so generally our choice of option will have limited effect

![image](https://user-images.githubusercontent.com/27824606/227295147-b32fe8e6-03da-4e96-8cf8-fdaf572ce58a.png)

**Comment by brianlangseth-NOAA** [comment]
@tsoutt and @KSten We are going with option 2 above but with a borrowing rule of 25 samples instead of 10, which are the red dots on the most recent figure with color. We haven't heard any concern from you about this (personally I like our approach) so we are assuming you are ok with it and are moving forward with this decision.

**Comment by tsoutt** [comment]
No objections. :-)
