### ISSUE TITLE
Remaining data tasks

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#60]
@okenk There are just a few remaining data tasks as we approach the deadline. 

**Ages**
- [x] CA Comm:  Should be in pacfin for 2010-2021. CAP hopes to be done with 2022 first week of May. May need to ask Chantel to pull later in the week so as not to have to ask again. Done in commit dff51d7
- [x] Triennial Survey: Both 1986 and 1998 will be released to Nancy Roberson before the data deadline. Can you check to see if these are up? If so can you incorporate?  Done so in commit 14db0ce
- [x] OR Comm/Rec:  Seem to be done. Will wait for Ali to provide for rec. Comm will be pulled with pull from PacFIN. Update Ali provided on 4/29. 
  - [x] Rec done in commit 4e3945b
  - [x] Com done in commit dff51d7
- [x] ASHOP: Might not have gotten all recent reads from Vanessa. Have 100 in 2021 from data she pulled. Will check when meet with Vanessa though may go only with what we currently have? Done in commit f55b2fa
- [x] WA rec: waiting on WDFW to update sport biodata. UPDATE: Kristen provided on 4/28. Commit 4e3945b

**Comment by okenk** [comment]
As of right now, there are not yet 1986 triennial age data.

**Comment by brianlangseth-NOAA** [comment]
As of 5/1 the triennial samples are in the data warehouse

**Comment by okenk** [comment]
Comp data in the data folder has been updated with 14db0ce
