### ISSUE TITLE
Incorporate data and change setup for model runs

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#62]
Skeleton of model running file is up per commit 916b337. We need to incorporate new data from the 2015 base and then update new settings to match current best practices and our planned approach. @okenk check off the following once it is incorporated into the set up for this cycle 

**Data**
- [x] Catches (Kiva)
- [x] Lcomps (Kiva)
- [x] Survey Acomps (Kiva) Update triennial comps
- [x] Fishery Acomps (Kiva)
- [x] Ageing error (not yet ready to incorporate) (Kiva)
- [x] Indices (main indices are available but some state specific indices not yet ready to incorporate) (Kiva)

**Parameterizations and Biology**
- [x] Selectivity blocks - First setup is as follows
TWL: 2001-2010, 2011-2022
CA NTWL: 2003-2020, 2021-2022
WA/OR NTWL: 2004-2014, 2015-2022 (though WA NTWL is mirrored to WA TWL)
CA rec: 2001-2022
OR rec: 2004-2014, 2015-2022 (same as NTWL)
WA rec: 2006-2022, 2021-2022 

 
- [x] Natural mortality (Kiva)
- [x] Maturity
- [x] Fecundity (Brian can do)
- [x] WL
- [x] Steepness

My suggestion is to keep the variance adjusts and lambda setups the same as was used for the 2015 model until we confirm our new settings and data run. Then from there we revisit these.

**Comment by okenk** [comment]
Is fecundity different? It looks like Jim also used E.J.'s dissertation which is the default, right?

**Comment by brianlangseth-NOAA** [comment]
Yes that is the default. Ive used eggs in the past, and I think the 2015 was linear instead. I planned to look over the options, which may just be confirming the same.

**Comment by okenk** [comment]
I am going through adding the age comps. I noticed some of them have very few samples and we might considering excluding them. Ones I flagged are:
- CA ASHOP (both ages and lengths)
- All age comps with sex = 0. If you don't want to eliminate these, I suggest randomly assigning a sex. This would be consistent with the approach for surveys, which probably have more unsexed fish, as surveys catch more of the young fish that are hard to sex.

Eliminating CA ASHOP would eliminate a figure panel that will likely have poor fits and low sample sizes, and could be distracting. Also there are so many fleets -> so many panels...

**Comment by okenk** [comment]
One other thing-- if we stick with separate ageing error for CAPS, ODFW, and WDFW, that information will need to be added to the length comps.

I think I finally have the double reads formatted correctly, but the max gradient is ~0.5 so something is amiss.

**Comment by brianlangseth-NOAA** [comment]
Confirmed on ageing error, those will be to be added to the comps. 

I think I forgot to say but our moving of recent CA ASHOP catches to Oregon removes all CA length and age comps thus those wont appear anymore.

**Comment by brianlangseth-NOAA** [comment]
We have incorporated these (removed sparse comps, used past (from 2015 assessment) ageing error matrix, past assessment used EJ's dissertation but the updated 2017 paper updates that)
