### ISSUE TITLE
Fixes to internal review document

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#76]
LIst of fixes to do before public submission. Based on our read, and Owen's and John Fields

Priority:
- [x] KIVA: Add estimates of survey biomass allocated by state into regional management considerations
- [x] Have WL female and male alpha parameter report out as scientific digits in the parameter table. Also for eggs alpha parameter. These three values read out as 0.000 currently
- [x] add disclaimer using ~01a.Rmd, when I try it the page number goes all wonky, probably because we dont currently have the executive summary~ 02Disclaimer.Rmd
~- [ ] Add reviewers into acknowledgements once we know them.~ Moved to post star tasks #77
 - [x] Noticed the WCGBTS as asymptotic selectivity was incorrectly applied to parameter 3 instead of 4. Fix and add to writing tables.
- [x] Include updated 2023 and 2024 projected values for projections into our model and updated teh time-series table

Hope to do by Monday:

- [x] KIVA to start: Executive summary

Comments from Owen:

- [x] Add second set of profile figures showing change across management targets. 
- [x] When updating selectivity figures, remove headers and add axis labels. 
- [x] Add an element to the bridging that aligns last bridge with model more similar to where we are at (probably a tuning one)
- [x] For M sensitivites that didn't converge (estimating male and female M; I dont think we need it for the male M prior), set male M phase to later and see if it improves
- [x] change the prior for male M to lognormal (because I tested this and it has no effect). 

Comments from Jim:

- [x] Update page margins per instructions at PEP team meeting (use 1in)
- [x] Regards bridging figures: clarify when its cumulative
- [x] Do something about the panel labels for the bottom rows of Figs 49-52, so they aren't overlapping

Comments from John:

- [x] BRIAN: Consider adding something to the uncertainties and problems section (something about M, perhaps something about global convergence and the amount of parameters). 
~- [ ] Consider adding a Kobe plot (is required in exec summary)~ In r4ss files and in executive summary

Others of varying degrees of importance:
- [x] make hyperlinks blue so that know when there is a link
- [x] Fix selectivity figure labelling of the washington fleet
- [x] If we confirm using inits from external estimates doesn't change model results say so in the growth section. Right now I dont say what the inits are. *Brian: There are sensitivities to these, model doesn't go to lowest NLL (see #75) so leave as is (currently inits are set from female growth from last model because we copied over separate male and female params when removing the offsets)*
- [x] Move labels in retro plots to be on the right
- [x] Some of the section references show up as ??
- [x] Ping state partners and await whitney's response to updating changes since the fishery was declared rebuilt
- [x] When cite the 2015 assessment use @thorson_status_2016 (because the assessment was a 2016 document)
- [x] In my historical comparison figure decide whether to keep 2001 or replace with 2002 because it appears the year of assessment differed from the year the report was published. Elsewhere we refer to 2002 so I suggest switch the figure to 2002.
- [x] Add citations to r4ss packages at first call
- [x] Confirm labels for M priors are consistent. Seems like there could be some mislabeling. 
- [x] Add citations from J. Budrick
- [x] Add survey maps (already exist for pre-recruit and wcgbts from data workshop) Brian note: Is this needed? I didn't see it in the TOR. Kiva: No I don't think it's required. It just seemed like it would be useful when I was reading through. (Not a year-by-year thing, just a single map per survey.) But I do not think it needs to be high priority.
  - [x] Our current figure 1 kind of does this. Might that suffice? Kiva: I was thinking of something that actually shows the range of the species. The density really clearly tapers off at Point Conception and is highest in northern WA, but there is no figure illustrating that right now.
- [x] BRIAN: Update figure legends that show all the fleets but cuts off labels (i.e. catches - figure 2)
- [x] The sensitivity figure could use a smaller text size for the caption. I could not figure out how to do that. Kiva note: may be easier to just make the height of the figure shorter when it is produced.
- [x] resolve scientific names at first occurrence

Things that would be nice but I couldn't figure out and need help with:
- [x] Line break between the Oregon landings (in 21f) and 'Historic Ocean Boat Landings and Discards (1979--2000)' header. I couldn't get it *Its a 4th level header so no easy workaround - leave as is*
- [x] Also line breaks for sub-section headers in the figures section (I ended up commenting these things out because I also couldn't figure it out) *Its a 4th level header so no easy workaround - leave as is*

Some additional sensitivities:
- [x] Bomb radiocarbon sensitivity?
- [x] BRIAN: M breakpoint sensitivity which is preference over linear ramp in the TOR, and which has a larger bracket to uncertainty for a potential decision table
- [x] Simpler selectivity block again and combine WA/OR trawl for 2000-2022 because selectivity was very similar. Im not sure why I didn't do that. 
- [x] Do WA/OR trawl as logistic in early period

**Comment by okenk** [comment]
For the Thorson assessment citation, are you proposing we rename the citation key? Is there a reason to do that? I guess it is just a find and replace all, but it is a find and replace all in a lot of rmd docs. The citation itself shows up correctly as 2016 in the compiled doc which seems like the main thing that needs to be right. The 2015 tag is in sa4ss.bib, which Kelli has recommended we don't edit.

**Comment by brianlangseth-NOAA** [comment]
@okenk I went and adjusted those all as I went through the document. My solution was to find/replace, and to add another reference to our canary.bib with 2016 instead of 2015 as the year in the reference and the tag.
