### ISSUE TITLE
Post-STAR pre-SSC draft action items

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#79]
- [x] Add STAR panel request 15 into the sensitivities section (run base with projections under low recrutiment scenario (average 2014-2019 recdevs)) Started with c20d264 and updated with three later commits. 
- [x] Update report with new base run (00a.R and the figures and tables section) (@brianlangseth-NOAA, you will need to rerun [these lines](https://github.com/pfmc-assessments/canary_2023/blob/main/code/canary_report_setup.R#L54-L60))
- [x] Update materials in figures_for_documents.R with the new base run (except M-I data weighting table)
- [x] Confirm any other figures and tables from the previous base are updated
- [x] Rerun sensitivities with the new base model
  - [x] still need to update figures and tables from sensitivities
  - [x] need to update some of the text of the runs and results (see issue #80)
  - [x] check whether we need to add survey removal sensitivities and sigmaR profiles into report. Right now these aren't incluced UPDATE: We've decided not to do these because they a) weren't requested and b) would be in the STAR panel report.

**Comment by brianlangseth-NOAA** [comment]
@okenk I plan to remove the post-STAR folder and just work from the pre-STAR one. Github will track changes so we could recreate if we ever needed to. I will probably rename "pre-STAR" to "write-up" since it now wont be just the pre-star version. Let me know if you foresee any issues with this. 

For sensitivities, Im inclined to rename the ones with the new base with a prefix of "STAR_", to ensure we are replacing each run with the new base, however, that is inconsistent with the aforementioned github self-tracking. Consequently, my actual plan is to rerun ALL of the sensitivities from the new base without renaming the folders (even the ones we dont necessarily use in the report) so as to have a consistent base model across the board. Again, let me know if you foresee any issues with this - or see a better, different, solution.

**Comment by okenk** [comment]
This all sounds good. It may be easier to have a sensitivities_post-STAR folder so you don't have to change all of the model names. But up to you since you are the one planning on rerunning things.

I will unignore the natural mortality profile figures so that you have access to them. Is there anything else you'd like to split up?

**Comment by brianlangseth-NOAA** [comment]
Could you start boxes 2-4 from above (i.e. set up the report writing scripts to access the new model and pull in the r4ss plots etc.)? 

When I tried to recompile the doc from last week, I noticed that the executive summary tables now have new columns names due to an update in the sa4ss version so those will need to be fixed (I assume you also get that error because I think we both updated sa4ss).

**Comment by brianlangseth-NOAA** [comment]
@okenk The sensitivity runs during the panel with abundance indices removed were not originally in the report. It is unclear to me whether the panel wanted those within the document - the runs during the week were intended to see if an extreme result could be obtained. Those runs do provide information that can be useful for understand data structure. 

Do you recall if we were tasked with adding those sensitivities in? Right now, Im not adding them in, but its easy enough to include later should we decide to

**Comment by okenk** [comment]
I don't think we were given direction either way, which I take to mean we do not need to include them in the document. My sense is they will be in the STAR panel report, so that is sufficient.
