### ISSUE TITLE
Edits to final assessment version

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#81]
- [x] The doi on the NMFS 1992 federal registry reference is incorrect. Replace with correct version if there is one. 
- [x] For table 22, the OFL, ABC, and ACL were as specified in regulations. At the September 2023 Council meeting, the values in the regulations were found to be in err (see document [G.8, Supplemental REVISED](https://www.pcouncil.org/documents/2023/08/g-8-attachment-1-joint-council-staff-and-nwfsc-report-on-technical-corrections-to-the-2023-2024-harvest-specifications.pdf/)). Do we need to update these values for Table 22 given Council action? ANSWER: Only the 2024 values were updated
- [x] For figure 139 need to add a part about the recruitment in the caption. Also, the recruitment labels should be millions. Its x1000 thousands, so  1 million.
- [x] Fix caption in figure 42 "b bridge"
- [x] Fix caption in figure 44. Its not a model version bridge comparison
- [x] For sensitivity figure captions that are updated cumulatively (starting with figure 43) say "from the X model" to indicate they aren't started from the 2015 model, which is the first in all figures. 
- [x] The caption for the decision table does not align with parts A and B within the table. Either change the legend (A is less catch and so is from P* = 0.4, not 0.45) or change the order of the table.
- [x] Remove Draft in disclaimer
- [x] Confirm whether the P* = 0.4 projection table needs to be included in the final report

**Comment by brianlangseth-NOAA** [comment]
@okenk If you have any other corrections we need to include, please add here. Ive incorporated all of the above, and plan to give the document one more look over. I will provide to Marlene (and John F.) once I work with Kelli on 508 compliance.

**Comment by okenk** [comment]
Thanks for asking-- this list looks pretty good to me! Onward!
