### ISSUE TITLE
Add statement about category designation

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#83]
From PEP meeting on 11/15

-Waiting for stated guidance before adding

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA see this [commit in sablefish](https://github.com/pfmc-assessments/sablefish/commit/2fe1b6ad3f7741c4eaa2c261ca3e35fb6bbdc7f4) for what @chantelwetzel-noaa added to the sablefish assessment.
